manifest:
  remotes:
    - name: franktheficus
      url-base: https://github.com/franktheficus
  projects:
    - name: zmk
      remote: franktheficus
      revision: with-tap-dance
      import: app/west.yml
  self:
    path: config
